# Generated by Django 5.0.6 on 2024-05-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_news_category_user_tasks_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
    ]
