# Generated by Django 5.0.6 on 2024-05-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_first_name_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
